### ISSUE TITLE
Sound and animation

### ISSUE THREAD

**Issue by Yungsaas** [lgkonline/so2money#1]
I have noticed that the sound and the animation of the cases are not synchronized.

- the sound starts when you push the button and not when the roll animation begins
- the animation doesnt slow down when the clicking sound does
- the sound of winning something comes too early

edit: 
- if you go back to the menu after opening a case the sound continues to play (dont know if that is intentional or not)

**Comment by lgkonline** [comment]
Fixed this points:
* the sound starts when you push the button and not when the roll animation begins
* if you go back to the menu after opening a case the sound continues to play (dont know if that is intentional or not)

Not fully fixed yet:
* the animation doesnt slow down when the clicking sound does
* if you go back to the menu after opening a case the sound continues to play (dont know if that is intentional or not)

**Comment by lgkonline** [comment]
Fixed
